# Generated by Django 4.1.3 on 2023-03-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(db_index=True, max_length=32)),
                ('long_name', models.CharField(max_length=64)),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=9)),
                ('record_type', models.CharField(choices=[('order', 'Order'), ('position', 'Position')], default='order', max_length=8)),
                ('entry_type', models.CharField(choices=[('manual', 'Manual'), ('auto_sync', 'Auto Sync')], default='manual', max_length=10)),
                ('avg_profit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('avg_duration', models.DurationField()),
                ('win_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_cagr', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=5)),
                ('position_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('entry_stamp', models.DateTimeField(auto_now_add=True)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('entry_amount', models.IntegerField()),
                ('exit_stamp', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('exit_amount', models.IntegerField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackrecord.portfolio')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataset.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop-limit', 'Stop Limit')], default='market', max_length=10)),
                ('order_action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('sent_stamp', models.DateTimeField(auto_now_add=True)),
                ('sent_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sent_amount', models.IntegerField()),
                ('filled_stamp', models.DateTimeField(blank=True, null=True)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('filled_amount', models.IntegerField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackrecord.portfolio')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trackrecord.position')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.symbol')),
            ],
        ),
    ]
