# Generated by Django 5.0.7 on 2024-07-21 04:32

import django.db.models.deletion
import vega.forms
import vega.models._ModelStubs
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=9)),
                ('record_type', models.CharField(choices=[('order', 'Order'), ('position', 'Position')], default='order', max_length=8)),
                ('entry_type', models.CharField(choices=[('manual', 'Manual'), ('auto_sync', 'Auto Sync')], default='manual', max_length=10)),
                ('allowed_roles', vega.forms.ChoiceArrayField(base_field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('subscriber', 'Subscriber'), ('guest', 'Guest')], default='owner', max_length=10), size=None)),
                ('avg_profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('smallest_profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('largest_profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('avg_loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('smallest_loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('largest_loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('avg_win_duration', models.DurationField(blank=True, null=True)),
                ('avg_loss_duration', models.DurationField(blank=True, null=True)),
                ('avg_wash_duration', models.DurationField(blank=True, null=True)),
                ('shortest_win_duration', models.DurationField(blank=True, null=True)),
                ('shortest_loss_duration', models.DurationField(blank=True, null=True)),
                ('shortest_wash_duration', models.DurationField(blank=True, null=True)),
                ('largest_win_duration', models.DurationField(blank=True, null=True)),
                ('largest_loss_duration', models.DurationField(blank=True, null=True)),
                ('largest_wash_duration', models.DurationField(blank=True, null=True)),
                ('win_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_cagr', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_wins', models.IntegerField(blank=True, null=True)),
                ('total_losses', models.IntegerField(blank=True, null=True)),
                ('total_washes', models.IntegerField(blank=True, null=True)),
                ('total_trades', models.IntegerField(blank=True, null=True)),
                ('open_trades', models.IntegerField(blank=True, null=True)),
                ('largest_wining_streak', models.IntegerField(blank=True, null=True)),
                ('largest_loosing_streak', models.IntegerField(blank=True, null=True)),
                ('largest_wash_streak', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
            bases=(models.Model, vega.models._ModelStubs.EventBridgeStub),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(choices=[('portfolio', 'Portfolio'), ('permission', 'Permission'), ('subscription', 'Subscription'), ('filled_order', 'Filled Order'), ('partial_order', 'Partial Order'), ('pending_order', 'Pending Order'), ('cancelled_order', 'Cancelled Order'), ('open_position', 'Open Position'), ('closed_position', 'Closed Position')], default='portfolio', max_length=15)),
                ('group', models.CharField(choices=[('portfolios', 'Portfolios'), ('permissions', 'Permissions'), ('subscriptions', 'Subscriptions'), ('orders', 'Orders'), ('positions', 'Positions'), ('securities', 'Securities'), ('symbols', 'Symbols')], default='portfolios', max_length=15)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('subscriber', 'Subscriber'), ('guest', 'Guest')], default='subscriber', max_length=10)),
                ('actions', vega.forms.ChoiceArrayField(base_field=models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('list', 'List'), ('update', 'Update'), ('delete', 'Delete')], default='view', max_length=6), size=None)),
                ('enabled', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', related_query_name='core.portfolio', to='trackrecord.portfolio')),
            ],
            options={
                'ordering': ['role', 'group', 'collection'],
                'abstract': False,
            },
            bases=(models.Model, vega.models._ModelStubs.EventBridgeStub),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('unknown', 'Unknown'), ('long', 'Long'), ('short', 'Short')], default='unknown', max_length=7)),
                ('position_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('entry_stamp', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('entry_amount', models.IntegerField()),
                ('entry_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('exit_stamp', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('exit_amount', models.IntegerField(blank=True, null=True)),
                ('exit_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('real_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('unreal_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('result_type', models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('win', 'Win'), ('loss', 'Loss'), ('wash', 'Wash')], max_length=7, null=True)),
                ('streak_group', models.BigIntegerField(blank=True, null=True)),
                ('streak_index', models.PositiveIntegerField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', related_query_name='core.portfolio', to='trackrecord.portfolio')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', related_query_name='core.symbol', to='dataset.symbol')),
            ],
            options={
                'ordering': ['exit_stamp', 'entry_stamp'],
                'abstract': False,
            },
            bases=(models.Model, vega.models._ModelStubs.EventBridgeStub),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop-limit', 'Stop Limit')], default='market', max_length=10)),
                ('order_action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('sent_stamp', models.DateTimeField()),
                ('sent_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('sent_amount', models.IntegerField()),
                ('filled_stamp', models.DateTimeField(blank=True, null=True)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('filled_amount', models.IntegerField(blank=True, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='core.symbol', to='dataset.symbol')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='core.portfolio', to='trackrecord.portfolio')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='core.position', to='trackrecord.position')),
            ],
            options={
                'ordering': ['filled_stamp', 'sent_stamp'],
                'abstract': False,
            },
            bases=(models.Model, vega.models._ModelStubs.EventBridgeStub),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('subscriber', 'Subscriber'), ('guest', 'Guest')], default='owner', max_length=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', related_query_name='core.portfolio', to='trackrecord.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', related_query_name='auth.user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, vega.models._ModelStubs.EventBridgeStub),
        ),
    ]
