# Generated by Django 4.0 on 2023-05-01 05:12

import core.forms
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('description', models.CharField(max_length=64)),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=9)),
                ('record_type', models.CharField(choices=[('order', 'Order'), ('position', 'Position')], default='order', max_length=8)),
                ('entry_type', models.CharField(choices=[('manual', 'Manual'), ('auto_sync', 'Auto Sync')], default='manual', max_length=10)),
                ('allowed_roles', core.forms.ChoiceArrayField(base_field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('subscriber', 'Subscriber'), ('guest', 'Guest')], default='owner', max_length=10), size=None)),
                ('avg_profit', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('avg_duration', models.DurationField(null=True)),
                ('win_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_cagr', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('subscriber', 'Subscriber'), ('guest', 'Guest')], default='owner', max_length=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='trackrecord.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=5)),
                ('position_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('entry_stamp', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('entry_amount', models.IntegerField()),
                ('exit_stamp', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('exit_amount', models.IntegerField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trackrecord.portfolio')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='dataset.symbol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(choices=[('portfolio', 'Portfolio'), ('permission', 'Permission'), ('subscription', 'Subscription'), ('filled_order', 'Filled Order'), ('partial_order', 'Partial Order'), ('pending_order', 'Pending Order'), ('cancelled_order', 'Cancelled Order'), ('open_position', 'Open Position'), ('closed_position', 'Closed Position')], default='portfolio', max_length=15)),
                ('group', models.CharField(choices=[('portfolio', 'Portfolio'), ('permission', 'Permission'), ('subscription', 'Subscription'), ('order', 'Order'), ('position', 'Position')], default='portfolio', max_length=15)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('subscriber', 'Subscriber'), ('guest', 'Guest')], default='subscriber', max_length=10)),
                ('actions', core.forms.ChoiceArrayField(base_field=models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('list', 'List'), ('update', 'Update'), ('delete', 'Delete')], default='view', max_length=6), size=None)),
                ('enabled', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='trackrecord.portfolio')),
            ],
            options={
                'ordering': ['role', 'group', 'collection'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop-limit', 'Stop Limit')], default='market', max_length=10)),
                ('order_action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('sent_stamp', models.DateTimeField()),
                ('sent_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('sent_amount', models.IntegerField()),
                ('filled_stamp', models.DateTimeField(blank=True, null=True)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('filled_amount', models.IntegerField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trackrecord.portfolio')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trackrecord.position')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dataset.symbol')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
