# Generated by Django 4.0 on 2023-06-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='trend_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('long', 'Long'), ('short', 'Short')], default='unknown', max_length=7),
        ),
    ]
