# Generated by Django 4.0 on 2023-04-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
