# Generated by Django 4.0 on 2023-05-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
