# Generated by Django 4.0 on 2023-04-24 04:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0002_order_limit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(choices=[('subscription', 'Subscription'), ('portfolio', 'Portfolio'), ('permission', 'Permission'), ('order', 'Order'), ('position', 'Position')], default='portfolio', max_length=12)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('subscriber', 'Subscriber'), ('guest', 'Guest')], default='subscriber', max_length=10)),
                ('actions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('update', 'Update'), ('delete', 'Delete')], default='view', max_length=6), size=None)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackrecord.portfolio')),
            ],
        ),
    ]
