# Generated by Django 4.1.3 on 2023-03-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0002_alter_portfolio_avg_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='avg_duration',
            field=models.DurationField(null=True),
        ),
    ]
