# Generated by Django 4.1.3 on 2023-03-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0003_alter_portfolio_avg_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='total_cagr',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='win_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
