# Generated by Django 4.0 on 2023-04-24 04:29

from django.db import migrations, models
import trackrecord.models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0003_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='actions',
            field=trackrecord.models.ChoiceArrayField(base_field=models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('update', 'Update'), ('delete', 'Delete')], default='view', max_length=6), size=None),
        ),
    ]
