# Generated by Django 4.0 on 2023-04-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0004_alter_permission_actions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['collection', 'role']},
        ),
    ]
