# Generated by Django 4.1.3 on 2023-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0004_alter_portfolio_total_cagr_alter_portfolio_win_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='entry_stamp',
            field=models.DateTimeField(),
        ),
    ]
