# Generated by Django 4.0 on 2023-04-24 06:52

import core.forms
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0005_alter_permission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='actions',
            field=core.forms.ChoiceArrayField(base_field=models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('list', 'List'), ('update', 'Update'), ('delete', 'Delete')], default='view', max_length=6), size=None),
        ),
        migrations.AlterField(
            model_name='permission',
            name='collection',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('permission', 'Permission'), ('subscription', 'Subscription'), ('filled_order', 'Filled Order'), ('partial_order', 'Partial Order'), ('pending_order', 'Pending Order'), ('cancelled_order', 'Cancelled Order'), ('open_position', 'Open Position'), ('closed_position', 'Closed Position')], default='portfolio', max_length=15),
        ),
        migrations.AlterField(
            model_name='permission',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='trackrecord.portfolio'),
        ),
    ]
