# Generated by Django 4.0 on 2023-04-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0006_alter_permission_actions_alter_permission_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('permission', 'Permission'), ('subscription', 'Subscription'), ('filled_order', 'Filled Order'), ('partial_order', 'Partial Order'), ('pending_order', 'Pending Order'), ('cancelled_order', 'Cancelled Order'), ('open_position', 'Open Position'), ('closed_position', 'Closed Position')], default='portfolio', max_length=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='allowed_roles',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('subscriber', 'Subscriber'), ('guest', 'Guest')], default=['owner'], max_length=10),
        ),
    ]
