# Generated by Django 4.1.3 on 2023-03-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0006_alter_position_exit_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='entry_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='exit_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
