# Generated by Django 4.1.3 on 2023-03-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0007_alter_position_entry_stamp_alter_position_exit_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='entry_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
