# Generated by Django 4.0 on 2023-04-26 13:30

import core.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0008_alter_portfolio_allowed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='allowed_roles',
            field=core.forms.ChoiceArrayField(base_field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('subscriber', 'Subscriber'), ('guest', 'Guest')], max_length=10), size=None),
        ),
    ]
