# Generated by Django 4.1.3 on 2023-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0008_alter_position_entry_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='entry_stamp',
            field=models.DateTimeField(),
        ),
    ]
