# Generated by Django 4.0 on 2023-04-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0010_alter_portfolio_allowed_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['role', 'group', 'collection']},
        ),
    ]
