# Generated by Django 4.0 on 2023-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0011_alter_permission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('permission', 'Permission'), ('subscription', 'Subscription'), ('order', 'Order'), ('position', 'Position')], default='portfolio', max_length=15),
        ),
    ]
