# Generated by Django 4.1.3 on 2023-03-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecord', '0011_executedorder_unexecutedorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecutedOrder',
        ),
        migrations.DeleteModel(
            name='UnexecutedOrder',
        ),
    ]
