AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Lambda-2016-10-31'
Description: >-
    A Django application on AWS Lambda that processes documents triggered by
    EventBridge.

Globals:
    Function:
        Timeout: 30

Resources:
    OrderCreatedLambda:
        Type: AWS::Serverless::Function
        Properties:
            Handler: orders.created_event
            CodeUri: ./lambdas/
            Runtime: python3.12
            # Layers:
            #     - !Ref ConfigLayer
            #     - !Ref VegaLayer
            # Environment:
            #     Variables:
            #         PYTHONPATH: "/opt:/opt/vega:/opt/config"
            # Events:
            #     EventBridgeEvent:
            #         Type: EventBridgeRule
            #         Properties:
            #             EventBusName: default
            #             Pattern:
            #                 source:
            #                     - aws.s3
            #                 detail-type:
            #                     - AWS API Call via CloudTrail
            #                 detail:
            #                     eventName:
            #                         - PutObject
            #                     requestParameters:
            #                         bucketName:
            #                             - Ref: DocumentBucket

    # DocumentBucket:
    #     Type: 'AWS::S3::Bucket'

    # ConfigLayer:
    #     Type: AWS::Lambda::LayerVersion
    #     Properties:
    #         LayerName: config
    #         Description: Config libraries for sam apps
    #         ContentUri: ../../libs/config
    #         CompatibleRuntimes:
    #             - python3.11
    #         # RetentionPolicy: Retain
    #     Metadata:
    #         BuildMethod: python3.11


    # VegaLayer:
    #     Type: AWS::Lambda::LayerVersion
    #     Properties:
    #         LayerName: vega
    #         Description: Model libraries for sam apps
    #         ContentUri: ../../libs/vega
    #         CompatibleRuntimes:
    #             - python3.11
    #         # RetentionPolicy: Retain
    #     Metadata:
    #         BuildMethod: python3.11
